services:

  wordpress:
    image: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - ./data-wordpress:/var/www/html
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`yourdomain.civit.ovh`)
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.tls.certresolver=prodresolver
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.services.wordpress.loadbalancer.server.port=80
    container_name: wordpress
  db-wp:
    image: mysql:8.0
    container_name: db-wp
    restart: always
    env_file:
      - .env
    volumes:
      - ./data-db:/var/lib/mysql
    networks:
      - proxy
    labels:
      - "traefik.enable=false"

networks:
  proxy:
    external: true