services:
  crowdsec:
    image: crowdsecurity/crowdsec
    restart: always
    container_name: crowdsec
    ports:
      - 127.0.0.1:8086:8080
    environment:
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/sshd crowdsecurity/linux
      - GID=${GID-1000}
      - TZ=Europe/Paris
      
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec-db:/var/lib/crowdsec/data/
      - ./crowdsec-config:/etc/crowdsec/
     # Journaux Ã  analyser
      - /var/log/traefik/:/var/log/traefik/:ro
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
